# Generated by Django 4.2.5 on 2023-10-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qr.profile'),
            preserve_default=False,
        ),
    ]
