# Generated by Django 4.2.5 on 2023-10-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0004_qrcode_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_link', models.URLField()),
                ('redirect_link', models.URLField(unique=True)),
            ],
        ),
    ]
