# Generated by Django 4.2.5 on 2023-10-09 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0005_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='original_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrcode',
            name='redirect_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
