# Generated by Django 4.2.5 on 2023-10-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0006_qrcode_original_link_qrcode_redirect_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='text',
        ),
    ]
