# Generated by Django 4.2.5 on 2023-10-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0007_remove_qrcode_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Redirect',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='redirect_link',
            field=models.URLField(unique=True),
        ),
    ]
